### ISSUE TITLE
SpringCloud教程第12篇：Hystrix Dashboard（F版本） - 方志朋的博客

### ISSUE THREAD

**Issue by forezp** [forezp/blog-comments#98]
https://www.fangzhipeng.com/springcloud/2018/08/12/sc-f12-dash.html 

 <p>在我的第四篇文章<a href="http://blog.csdn.net/forezp/article/details/69934399">断路器</a>讲述了如何使用断路器，并简单的介绍了下Hystrix Dashboard组件，这篇文章更加详细的介绍Hystrix Dashboard。</p>

**Comment by zhongguangxi** [comment]
打开locahost:8762/hystrix 可以看见以下界面：这里localhost漏了一个l，用的人注意下，我刚开始就是无脑复制，一直访问不通

**Comment by Reason0701** [comment]
> @qq32933432
> 打开locahost:8762/hystrix 可以看见以下界面：这里localhost漏了一个l，用的人注意下，我刚开始就是无脑复制，一直访问不通

哈哈，我也是，谢谢提醒

**Comment by pisory** [comment]
http://localhost:8762/actuator/hystrix.stream   404 error
好像要在启动类加上registrationBean的url才行

**Comment by tommyliu86** [comment]
>springboot 2.X以后actuator的endpoints需要手动开启，直接访问/actuator/hystrix.stream会报*404 error*
需要在配置中配置
```
management:
  endpoints:
    web:
      exposure:
        include: ['hystrix-stream'] or ‘*’
```
